### ISSUE TITLE
DB Encryption on PROD

### ISSUE THREAD

**Issue by srijan-esm** [esmagico/epic-global-devops#40]
# Task
- [x] connection to different VM db
- [x] SSL connection on PostgreSQL
- [x] Testing through services
- [x] Dbeaver

## VM1
- Set Inbound rule for Port 5432 on azure for VM2 IP only 
<img width="579" alt="Image" src="https://github.com/user-attachments/assets/8fba5568-623b-4fed-bd01-622cffa380a0" />

- Create docker-compose for dB
```
services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres_conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres_conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres_conf/ssl/server.crt:/etc/postgresql/server.crt
      - ./postgres_conf/ssl/server.key:/etc/postgresql/server.key

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}

volumes:
  db:
```
Need to map this time to connect from another DB

## VM2:

```
docker run -it --rm postgres:17.2 \
  psql "sslmode=require host=20.235.243.81 dbname=my-db user=admin"
```

### Generating SSL certs for the postgres

```
mkdir -p ./postgres_conf/ssl
cd ./postgres_conf/ssl

openssl req -new -x509 -days 365 \
  -nodes -text \
  -out server.crt \
  -keyout server.key \
  -subj "/CN=your-db-domain.com"

sudo chown 999:999 server.key
sudo chmod 600 server.key
chmod 644 server.crt
```

directory structure looks like this
```
postgres_conf/
├── postgresql.conf
├── pg_hba.conf
└── ssl/
    ├── server.crt
    └── server.key

```
