### ISSUE TITLE
Vector DB setup 

### ISSUE THREAD

**Issue by srijan-esm** [esmagico/epic-global-devops#52]
WIP

**Comment by shivanshEsmagico** [comment]
@AnvanshSingh's bandwidth needed.

**Comment by srijan-esm** [comment]
Changed docker image tag
- form  `latest` to `1.31.1-509541d.amd64` 
- issues:
  -  data lost 
  - RCA needed

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/aa230556-b6f7-4743-a90e-194fd60c73bd" />

**Comment by srijan-esm** [comment]
Old Setup 
- wrong envs on old setup with latest tag
```
services:
  weaviate:
    image: semitechnologies/weaviate:1.31.1-509541d.amd64
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      WAVIATE_QUERY_DEFAULTS_LIMIT: ${WAVIATE_QUERY_DEFAULTS_LIMIT:?WAVIATE_QUERY_DEFAULTS_LIMIT is not set}
      WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:?WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED is not set}
      WAVIATE_PERSISTENCE_DATA_PATH: ${WAVIATE_PERSISTENCE_DATA_PATH:?WAVIATE_PERSISTENCE_DATA_PATH is not set}
      WAVIATE_DEFAULT_VECTORIZER_MODULE: ${WAVIATE_DEFAULT_VECTORIZER_MODULE:?WAVIATE_DEFAULT_VECTORIZER_MODULE is not set}
      WAVIATE_ENABLE_MODULES: ${WAVIATE_ENABLE_MODULES:?WAVIATE_ENABLE_MODULES is not set}
      WAVIATE_CLUSTER_HOSTNAME: ${WAVIATE_CLUSTER_HOSTNAME:?WAVIATE_CLUSTER_HOSTNAME is not set}
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
```
